name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild clean test -workspace "LetsGo.xcworkspace" -scheme "LetsGo" -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0'

